### ISSUE TITLE
when we reconstruct vcfs during the germline filter step, we excluded the 2 last columns

### ISSUE THREAD

**Issue by lincoln-harris** [czbiohub/cerebra#15]
- _FORMAT_ and this wierd _20_ field dont make the cut...
- probably want to sub out my janky vcf parsing/writing functions for something more official
- ie. pyVCF or VCFpy

**Comment by lincoln-harris** [comment]
none of these germline_filtered fuckers are gonna work with downstream modules (ie. `get_aa_mutations`, `get_mutationcounts_table`) bc they have the wrong number of header fields

**Comment by rvanheusden** [comment]
Fixed in #rohan-dev

**Comment by rvanheusden** [comment]
Fixed by 48fd43fc4b6634fb1ec0b4d4e2286164125b9454.
