### ISSUE TITLE
during vcf reconstruction (germline filter) step, we're literally appending the same vcf header to all our files

### ISSUE THREAD

**Issue by lincoln-harris** [czbiohub/cerebra#16]
- related to #15 
- this is not ideal, we need _INFO_ field to do any sort of coverage analysis

**Comment by rvanheusden** [comment]
Fixed in #rohan-dev

**Comment by rvanheusden** [comment]
Fixed by 48fd43fc4b6634fb1ec0b4d4e2286164125b9454.
