### ISSUE TITLE
Supporting different types of annotation GTFs

### ISSUE THREAD

**Issue by rvanheusden** [czbiohub/cerebra#36]
find_aa_mutations soft-requires gencode’s gtf annotation, which for whatever reason has 5 comment lines at the top which pandas doesn’t like
might be good to document somewhere that those have to be removed from the file or add handling so that comment lines are cut off
right now there’s a disparity; mutation_counts’ annotation read_csv call is normal (hg38.gtf), while find_aa_mutations’ has to use `skiprows=5` (gencode .gtf)

**Comment by lincoln-harris** [comment]
this explains #41

**Comment by lincoln-harris** [comment]
this is (finally) addressed by #100
