### ISSUE TITLE
Review comments on CONTRIBUTING.md

### ISSUE THREAD

**Issue by afrubin** [czbiohub/cerebra#82]
The CONTRIBUTING.md document includes most of the required material, but there are a few issues.

The links in the document lead to the site home pages rather than the specified pages due to misplaced `>`. The document would benefit from including additional links, such as a link to the relevant GitHub documentation in the first "Get Started!" list item.

This document has very different installation instructions to the README. They should be harmonized, and it will probably be simpler to maintain if CONTRIBUTING refers the user to the README, with notes about changes required to create a dev environment. It's quite confusing to have one document require conda and another require virtualenvwrapper. Ideally both should just use standard library venv.

This document specifies tox but the main project seems to use pytest. The Tips section uses unittest. The project should pick one testing framework and stick to it throughout.

https://github.com/openjournals/joss-reviews/issues/2432

**Comment by afrubin** [comment]
This issue was closed as part of the PR, but was not actually resolved.

**Comment by lincoln-harris** [comment]
@lincoln-harris update https://github.com/czbiohub/cerebra/blob/master/CONTRIBUTING.md

**Comment by lincoln-harris** [comment]
@afrubin checkout 283dfe2 to see if this has been properly addressed?

**Comment by afrubin** [comment]
This looks much better. The "Pull Request Guidelines" section still needs some work, though. For example, it doesn't specify test coverage and README.rst doesn't exist (you have a README.md).

**Comment by afrubin** [comment]
The Contributing section in the README mentions a CONTRIBUTING.md that no longer exists.

**Comment by lincoln-harris** [comment]
@afrubin closing this issue, pending any objections
