### ISSUE TITLE
improve testing speed

### ISSUE THREAD

**Issue by lincoln-harris** [czbiohub/cerebra#85]
the biggest thing to do here is gonna be removing that massive hg38.fa chr7 / chr12 file. 

either reworking the tests to get around using the .fa entirely or else figuring out how to further compress it

**Comment by rvanheusden** [comment]
One option that you could consider is what I ended up doing for the variant counting test, which is to simply use a subset of these large reference files.

https://github.com/czbiohub/cerebra/blob/4e5d5cff517a094a073f42c3b2ba8410ece49811/tests/test_count_variants.py#L23-L25

This test, for example, uses CosmicGenomeScreensMutantExport.**min**.tsv, which is just a subset of the original file. I forget what proportion it is exactly—maybe around 10% of the original or so. What I tried to do was just get the file size down such that it would only take about a second or so to load into memory.

The main caveat is that you have to ensure that tests using this strategy don't rely on all of the data being present.

**Comment by lincoln-harris** [comment]
yeah thats essential what i did with `test_find_peptide_variants_modules`, for example. https://github.com/czbiohub/cerebra/blob/cf5403536b2797caf3093a2552d3e48a00fd1236/tests/test_find_peptide_variants_modules.py#L20-L21

`GRCh38_limited.fa.gz` is just chr7 and chr12 I believe. Right now that file is huge -- 84Mb, gzipped. 
Even if I limit it to just one of those chromosomes, its still gonna be like 40Mb

**Comment by lincoln-harris** [comment]
another option is adding in `pytest` [fixtures](https://docs.pytest.org/en/stable/fixture.html#fixtures) to speed things up. essentially this allows you to treat `pytest` variables/objects as globals and access them across different test cases, circumventing the need to do lengthy object rebuild steps between tests
